FROM ubuntu:22.04

ARG QT_VERSION=6.8.3
ARG QT_MODULES="qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors"

ENV DEBIAN_FRONTEND noninteractive

ENV DISPLAY :99

ENV QT_PATH /opt/Qt
ENV QT_DESKTOP $QT_PATH/${QT_VERSION}/gcc_64

ENV PATH /usr/lib/ccache:$QT_DESKTOP/bin:$PATH




RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        sudo \
        locate \
        xterm \
        vim

# Create a non-root user and group inside the container with specified UID and GID
ARG CONTAINER_UID
ARG CONTAINER_GID
ARG CONTAINER_USER
RUN groupadd -r -g $CONTAINER_GID $CONTAINER_USER && \
    useradd -r -g $CONTAINER_USER -u $CONTAINER_UID -m $CONTAINER_USER && \
    usermod -aG dialout $CONTAINER_USER && \
    usermod -aG video ${CONTAINER_USER}

# No password required
RUN echo "${CONTAINER_USER} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${CONTAINER_USER}
RUN chmod 0440 /etc/sudoers.d/${CONTAINER_USER}





COPY tools/setup/install-dependencies-debian.sh /tmp/qt/
RUN /tmp/qt/install-dependencies-debian.sh

COPY tools/setup/install-qt-debian.sh /tmp/qt/
RUN /tmp/qt/install-qt-debian.sh

RUN locale-gen en_US.UTF-8 && dpkg-reconfigure locales

RUN git config --global --add safe.directory /project/source

WORKDIR /project/build
RUN mkdir -p /project && chown -R ${CONTAINER_USER}:${CONTAINER_USER} /project
USER $CONTAINER_USER

CMD cmake -S /project/source -B . -G Ninja -DCMAKE_BUILD_TYPE=Release && \
    cmake --build . --target all --config Release && \
    cmake --install . --config Release
